//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Modulo_Administracion.WSPSA4 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonaServiceA4SoapBinding", Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class PersonaServiceA4 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dummyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersonaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonaServiceA4() {
            this.Url = global::Modulo_Administracion.Properties.Settings.Default.Modulo_Administracion_WSPSA4_PersonaServiceA4;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dummyCompletedEventHandler dummyCompleted;
        
        /// <remarks/>
        public event getPersonaCompletedEventHandler getPersonaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a4.soap.ws.server.puc.sr/", ResponseNamespace="http://a4.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dummyReturn dummy() {
            object[] results = this.Invoke("dummy", new object[0]);
            return ((dummyReturn)(results[0]));
        }
        
        /// <remarks/>
        public void dummyAsync() {
            this.dummyAsync(null);
        }
        
        /// <remarks/>
        public void dummyAsync(object userState) {
            if ((this.dummyOperationCompleted == null)) {
                this.dummyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndummyOperationCompleted);
            }
            this.InvokeAsync("dummy", new object[0], this.dummyOperationCompleted, userState);
        }
        
        private void OndummyOperationCompleted(object arg) {
            if ((this.dummyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dummyCompleted(this, new dummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a4.soap.ws.server.puc.sr/", ResponseNamespace="http://a4.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("personaReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaReturn getPersona([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sign, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cuitRepresentada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long idPersona) {
            object[] results = this.Invoke("getPersona", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona});
            return ((personaReturn)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona) {
            this.getPersonaAsync(token, sign, cuitRepresentada, idPersona, null);
        }
        
        /// <remarks/>
        public void getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona, object userState) {
            if ((this.getPersonaOperationCompleted == null)) {
                this.getPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonaOperationCompleted);
            }
            this.InvokeAsync("getPersona", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona}, this.getPersonaOperationCompleted, userState);
        }
        
        private void OngetPersonaOperationCompleted(object arg) {
            if ((this.getPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonaCompleted(this, new getPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class dummyReturn {
        
        private string appserverField;
        
        private string authserverField;
        
        private string dbserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                this.appserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                this.authserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                this.dbserverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class telefono {
        
        private long numeroField;
        
        private bool numeroFieldSpecified;
        
        private string tipoLineaField;
        
        private string tipoTelefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoLinea {
            get {
                return this.tipoLineaField;
            }
            set {
                this.tipoLineaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoTelefono {
            get {
                return this.tipoTelefonoField;
            }
            set {
                this.tipoTelefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class relacion {
        
        private System.DateTime ffRelacionField;
        
        private bool ffRelacionFieldSpecified;
        
        private System.DateTime ffVencimientoField;
        
        private bool ffVencimientoFieldSpecified;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private long idPersonaAsociadaField;
        
        private bool idPersonaAsociadaFieldSpecified;
        
        private string subtipoRelacionField;
        
        private string tipoRelacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ffRelacion {
            get {
                return this.ffRelacionField;
            }
            set {
                this.ffRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffRelacionSpecified {
            get {
                return this.ffRelacionFieldSpecified;
            }
            set {
                this.ffRelacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ffVencimiento {
            get {
                return this.ffVencimientoField;
            }
            set {
                this.ffVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffVencimientoSpecified {
            get {
                return this.ffVencimientoFieldSpecified;
            }
            set {
                this.ffVencimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersonaAsociada {
            get {
                return this.idPersonaAsociadaField;
            }
            set {
                this.idPersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaAsociadaSpecified {
            get {
                return this.idPersonaAsociadaFieldSpecified;
            }
            set {
                this.idPersonaAsociadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subtipoRelacion {
            get {
                return this.subtipoRelacionField;
            }
            set {
                this.subtipoRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoRelacion {
            get {
                return this.tipoRelacionField;
            }
            set {
                this.tipoRelacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class regimen {
        
        private string descripcionRegimenField;
        
        private int diaPeriodoField;
        
        private bool diaPeriodoFieldSpecified;
        
        private string estadoField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int idRegimenField;
        
        private bool idRegimenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        private string tipoRegimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionRegimen {
            get {
                return this.descripcionRegimenField;
            }
            set {
                this.descripcionRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int diaPeriodo {
            get {
                return this.diaPeriodoField;
            }
            set {
                this.diaPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified {
            get {
                return this.diaPeriodoFieldSpecified;
            }
            set {
                this.diaPeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRegimen {
            get {
                return this.idRegimenField;
            }
            set {
                this.idRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegimenSpecified {
            get {
                return this.idRegimenFieldSpecified;
            }
            set {
                this.idRegimenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoRegimen {
            get {
                return this.tipoRegimenField;
            }
            set {
                this.tipoRegimenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class impuesto {
        
        private string descripcionImpuestoField;
        
        private int diaPeriodoField;
        
        private bool diaPeriodoFieldSpecified;
        
        private string estadoField;
        
        private System.DateTime ffInscripcionField;
        
        private bool ffInscripcionFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionImpuesto {
            get {
                return this.descripcionImpuestoField;
            }
            set {
                this.descripcionImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int diaPeriodo {
            get {
                return this.diaPeriodoField;
            }
            set {
                this.diaPeriodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaPeriodoSpecified {
            get {
                return this.diaPeriodoFieldSpecified;
            }
            set {
                this.diaPeriodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ffInscripcion {
            get {
                return this.ffInscripcionField;
            }
            set {
                this.ffInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffInscripcionSpecified {
            get {
                return this.ffInscripcionFieldSpecified;
            }
            set {
                this.ffInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class email {
        
        private string direccionField;
        
        private string estadoField;
        
        private string tipoEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoEmail {
            get {
                return this.tipoEmailField;
            }
            set {
                this.tipoEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class domicilio {
        
        private string codPostalField;
        
        private string datoAdicionalField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private string tipoDatoAdicionalField;
        
        private string tipoDomicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datoAdicional {
            get {
                return this.datoAdicionalField;
            }
            set {
                this.datoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionProvincia {
            get {
                return this.descripcionProvinciaField;
            }
            set {
                this.descripcionProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified {
            get {
                return this.ordenFieldSpecified;
            }
            set {
                this.ordenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDatoAdicional {
            get {
                return this.tipoDatoAdicionalField;
            }
            set {
                this.tipoDatoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDomicilio {
            get {
                return this.tipoDomicilioField;
            }
            set {
                this.tipoDomicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class dependencia {
        
        private string descripcionDependenciaField;
        
        private int idDependenciaField;
        
        private bool idDependenciaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionDependencia {
            get {
                return this.descripcionDependenciaField;
            }
            set {
                this.descripcionDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDependencia {
            get {
                return this.idDependenciaField;
            }
            set {
                this.idDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDependenciaSpecified {
            get {
                return this.idDependenciaFieldSpecified;
            }
            set {
                this.idDependenciaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class categoria {
        
        private string descripcionCategoriaField;
        
        private string estadoField;
        
        private int idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                this.descripcionCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified {
            get {
                return this.idCategoriaFieldSpecified;
            }
            set {
                this.idCategoriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class actividad {
        
        private string descripcionActividadField;
        
        private long idActividadField;
        
        private bool idActividadFieldSpecified;
        
        private int nomencladorField;
        
        private bool nomencladorFieldSpecified;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionActividad {
            get {
                return this.descripcionActividadField;
            }
            set {
                this.descripcionActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idActividadSpecified {
            get {
                return this.idActividadFieldSpecified;
            }
            set {
                this.idActividadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nomenclador {
            get {
                return this.nomencladorField;
            }
            set {
                this.nomencladorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomencladorSpecified {
            get {
                return this.nomencladorFieldSpecified;
            }
            set {
                this.nomencladorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified {
            get {
                return this.ordenFieldSpecified;
            }
            set {
                this.ordenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class persona {
        
        private actividad[] actividadField;
        
        private string apellidoField;
        
        private int cantidadSociosEmpresaMonoField;
        
        private bool cantidadSociosEmpresaMonoFieldSpecified;
        
        private categoria[] categoriaField;
        
        private System.Nullable<long>[] claveInactivaAsociadaField;
        
        private dependencia dependenciaField;
        
        private domicilio[] domicilioField;
        
        private email[] emailField;
        
        private string estadoClaveField;
        
        private System.DateTime fechaContratoSocialField;
        
        private bool fechaContratoSocialFieldSpecified;
        
        private System.DateTime fechaFallecimientoField;
        
        private bool fechaFallecimientoFieldSpecified;
        
        private System.DateTime fechaInscripcionField;
        
        private bool fechaInscripcionFieldSpecified;
        
        private System.DateTime fechaJubiladoField;
        
        private bool fechaJubiladoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private System.DateTime fechaVencimientoMigracionField;
        
        private bool fechaVencimientoMigracionFieldSpecified;
        
        private string formaJuridicaField;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private impuesto[] impuestoField;
        
        private int leyJubilacionField;
        
        private bool leyJubilacionFieldSpecified;
        
        private string localidadInscripcionField;
        
        private int mesCierreField;
        
        private bool mesCierreFieldSpecified;
        
        private string nombreField;
        
        private string numeroDocumentoField;
        
        private long numeroInscripcionField;
        
        private bool numeroInscripcionFieldSpecified;
        
        private string organismoInscripcionField;
        
        private string organismoOriginanteField;
        
        private double porcentajeCapitalNacionalField;
        
        private bool porcentajeCapitalNacionalFieldSpecified;
        
        private string provinciaInscripcionField;
        
        private string razonSocialField;
        
        private regimen[] regimenField;
        
        private relacion[] relacionField;
        
        private string sexoField;
        
        private telefono[] telefonoField;
        
        private string tipoClaveField;
        
        private string tipoDocumentoField;
        
        private string tipoOrganismoOriginanteField;
        
        private string tipoPersonaField;
        
        private string tipoResidenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public actividad[] actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadSociosEmpresaMono {
            get {
                return this.cantidadSociosEmpresaMonoField;
            }
            set {
                this.cantidadSociosEmpresaMonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSociosEmpresaMonoSpecified {
            get {
                return this.cantidadSociosEmpresaMonoFieldSpecified;
            }
            set {
                this.cantidadSociosEmpresaMonoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categoria", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public categoria[] categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long>[] claveInactivaAsociada {
            get {
                return this.claveInactivaAsociadaField;
            }
            set {
                this.claveInactivaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dependencia dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("domicilio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public domicilio[] domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public email[] email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoClave {
            get {
                return this.estadoClaveField;
            }
            set {
                this.estadoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoSocial {
            get {
                return this.fechaContratoSocialField;
            }
            set {
                this.fechaContratoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoSocialSpecified {
            get {
                return this.fechaContratoSocialFieldSpecified;
            }
            set {
                this.fechaContratoSocialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFallecimiento {
            get {
                return this.fechaFallecimientoField;
            }
            set {
                this.fechaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified {
            get {
                return this.fechaFallecimientoFieldSpecified;
            }
            set {
                this.fechaFallecimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaInscripcion {
            get {
                return this.fechaInscripcionField;
            }
            set {
                this.fechaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInscripcionSpecified {
            get {
                return this.fechaInscripcionFieldSpecified;
            }
            set {
                this.fechaInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaJubilado {
            get {
                return this.fechaJubiladoField;
            }
            set {
                this.fechaJubiladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaJubiladoSpecified {
            get {
                return this.fechaJubiladoFieldSpecified;
            }
            set {
                this.fechaJubiladoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaVencimientoMigracion {
            get {
                return this.fechaVencimientoMigracionField;
            }
            set {
                this.fechaVencimientoMigracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoMigracionSpecified {
            get {
                return this.fechaVencimientoMigracionFieldSpecified;
            }
            set {
                this.fechaVencimientoMigracionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string formaJuridica {
            get {
                return this.formaJuridicaField;
            }
            set {
                this.formaJuridicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int leyJubilacion {
            get {
                return this.leyJubilacionField;
            }
            set {
                this.leyJubilacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leyJubilacionSpecified {
            get {
                return this.leyJubilacionFieldSpecified;
            }
            set {
                this.leyJubilacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localidadInscripcion {
            get {
                return this.localidadInscripcionField;
            }
            set {
                this.localidadInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mesCierre {
            get {
                return this.mesCierreField;
            }
            set {
                this.mesCierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesCierreSpecified {
            get {
                return this.mesCierreFieldSpecified;
            }
            set {
                this.mesCierreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long numeroInscripcion {
            get {
                return this.numeroInscripcionField;
            }
            set {
                this.numeroInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroInscripcionSpecified {
            get {
                return this.numeroInscripcionFieldSpecified;
            }
            set {
                this.numeroInscripcionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string organismoInscripcion {
            get {
                return this.organismoInscripcionField;
            }
            set {
                this.organismoInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string organismoOriginante {
            get {
                return this.organismoOriginanteField;
            }
            set {
                this.organismoOriginanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double porcentajeCapitalNacional {
            get {
                return this.porcentajeCapitalNacionalField;
            }
            set {
                this.porcentajeCapitalNacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porcentajeCapitalNacionalSpecified {
            get {
                return this.porcentajeCapitalNacionalFieldSpecified;
            }
            set {
                this.porcentajeCapitalNacionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string provinciaInscripcion {
            get {
                return this.provinciaInscripcionField;
            }
            set {
                this.provinciaInscripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regimen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public regimen[] regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public relacion[] relacion {
            get {
                return this.relacionField;
            }
            set {
                this.relacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefono", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public telefono[] telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoClave {
            get {
                return this.tipoClaveField;
            }
            set {
                this.tipoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoOrganismoOriginante {
            get {
                return this.tipoOrganismoOriginanteField;
            }
            set {
                this.tipoOrganismoOriginanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoResidencia {
            get {
                return this.tipoResidenciaField;
            }
            set {
                this.tipoResidenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class metadata {
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private string servidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a4.soap.ws.server.puc.sr/")]
    public partial class personaReturn {
        
        private metadata metadataField;
        
        private persona personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public persona persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void dummyCompletedEventHandler(object sender, dummyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dummyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dummyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dummyReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dummyReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPersonaCompletedEventHandler(object sender, getPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591